#!/bin/bash

if [ $# -ne 1 ]; then
  echo $0 [package name]
  exit 1
fi

file=$(readlink -f "$1")
actual=$(readlink -f "$(dirname "$0")")
cd "$actual"

rm -f $(find -name "*~")

tar --owner=root --group=root -cvvzf "$file" api app fragment.png index.html \
  rservr-rabbit2.png rservr.css user
